Features/hoverlabelheight
strattonbrazil/busyimg pull request #25
Opened 2021-02-11 19:08 UTC by Strattonshrugged

Added height variable to read label reference, adjusts vertical position of label to be closer to cursor on names w/o an origin

fixes #23 

Also added metadata and image files for warp-core-cafe

![marioSnippet](https://user-images.githubusercontent.com/14046088/107685872-62c68a80-6c59-11eb-9840-82795ad39549.jpg)

2021-02-11 20:30 UTC, strattonbrazil requested changes
Change looks good, but I think we should make a similar change for the other y-check. 

Also, I think the warp-core-cafe.jpg image is too low of a resolution. It also waits much of that density on that large border. Can we use [this asset](http://www.jeffcarlisle.com/files/images/CharCon2018_05B_forweb01E.jpg)? It drops the border while still having the artist attribution. I think the existing size is probably fine, too.

2021-02-11 20:30 UTC, strattonbrazil commented on src/BusyImage.tsx
>        setHoveredLabelY(ev.clientY - rect.y + 10);
I think both upper and lower halves of the image should take the label height into account. There's less gap in the upper section, but it's inconsistent depending on if there's extra data.

2021-02-11 20:35 UTC, Strattonshrugged commented
kk, I'll dump the border and make sure we keep the artists name.

Also I think I just updated a pull request the same instant you sent this.
Weird timing.

On Thu, Feb 11, 2021 at 12:30 PM Josh Stratton <notifications@github.com>
wrote:

> *@strattonbrazil* requested changes on this pull request.
>
> Change looks good, but I think we should make a similar change for the
> other y-check.
>
> Also, I think the warp-core-cafe.jpg image is too low of a resolution. It
> also waits much of that density on that large border. Can we use this
> asset
> <http://www.jeffcarlisle.com/files/images/CharCon2018_05B_forweb01E.jpg>?
> It drops the border while still having the artist attribution. I think the
> existing size is probably fine, too.
> ------------------------------
>
> In src/BusyImage.tsx
> <https://github.com/strattonbrazil/busyimg/pull/25#discussion_r574803418>:
>
> >
>      if (ev.clientX + ev.currentTarget.scrollLeft > ev.currentTarget.scrollWidth/2){
>        setHoveredLabelX(ev.clientX - rect.x + ev.currentTarget.scrollLeft - maxLabelWidth);
>      } else {
>        setHoveredLabelX(ev.clientX - rect.x + ev.currentTarget.scrollLeft + 10);
>      };
>      if (ev.clientY - rect.y > ev.currentTarget.scrollHeight/2){
> -      setHoveredLabelY(ev.clientY - + rect.y - 100);
> +      setHoveredLabelY(ev.clientY - rect.y - labelHeight);
>      } else {
>        setHoveredLabelY(ev.clientY - rect.y + 10);
>
> I think both upper and lower halves of the image should take the label
> height into account. There's less gap in the upper section, but it's
> inconsistent depending on if there's extra data.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/strattonbrazil/busyimg/pull/25#pullrequestreview-588955023>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLFHCAGOVYR6SNDAZXES33S6Q457ANCNFSM4XPMEP4A>
> .
>

2021-02-12 17:19 UTC, Strattonshrugged commented
I guess I'm confused about taking the labelheight into account if the cursor is in the top half, I just dropped the +10 adjustment and it seems pretty tight without overlapping the label.

The +10 x-axis adjustment still exists on the left to keep the cursor from overlapping the label. If you want this closer on the left-bottom I can make it check for which quartile it's in instead of just top/bottom left/right, it'd be pretty easy I think.

2021-02-12 19:40 UTC, strattonbrazil commented
I must have been testing on another branch. Changes look good.

2021-02-12 19:41 UTC, merged